"""Generated by `asas new`. This is a normal pydantic-settings object —
extend it freely. Reads matching environment variables (case-insensitive)
and a local `.env` file automatically."""

from pydantic_settings import BaseSettings, SettingsConfigDict


class AppSettings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    database_url: str = "sqlite:///./app.db"
    rate_limit_enabled: bool = True
    rate_limit_overrides: str = ""
